const CONFIG = {
    pageTitle: "Crushifier",
    popupTitle: '😏😏😏',
    description: `I'm assuming you're here because you've been sent a link to this page by someone you know.`,
    introButton: 'They want to ask you something...',
    title: 'Will you go out with me?',
    yesBtn: 'Yess 🥺',
    noBtn: 'No :3',
    question: 'Glad to know you feel the same way 😘😘 \n Now.. tell me why you love me ?',
    sendBtn: 'Send',
    reply: 'Cuz what\'s there to not love about you? You\'re so cute, funny, and smart. You\'re the best thing that\'s ever happened to me. I love you so much 😘😘😘',
    messPop: 'I know. I\'m just that good 😎😎😎',
    messDesc: 'Now we\'re together officially 👉👈',
    btnAccept: 'Okiiiiieeee <3',
    redirect: 'https://github.com/TheGuyDangerous/Crushifier',
}
